//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuzikEnstrumaniDukkani.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enstrumanlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Enstrumanlar()
        {
            this.Siparis_Detay = new HashSet<Siparis_Detay>();
        }
    
        public int Id { get; set; }
        public string Ad { get; set; }
        public int Kategori_Id { get; set; }
        public string Uretim_Yeri { get; set; }
        public int Stok { get; set; }
        public int Fiyat { get; set; }
    
        public virtual Enstruman_Kategorileri Enstruman_Kategorileri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Siparis_Detay> Siparis_Detay { get; set; }
    }
}
