//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuzikEnstrumaniDukkani.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MuzikEnstrumaniDukkaniEntities : DbContext
    {
        public MuzikEnstrumaniDukkaniEntities()
            : base("name=MuzikEnstrumaniDukkaniEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Destek_Kategorileri> Destek_Kategorileri { get; set; }
        public virtual DbSet<Destek_Talepleri> Destek_Talepleri { get; set; }
        public virtual DbSet<Enstruman_Kategorileri> Enstruman_Kategorileri { get; set; }
        public virtual DbSet<Enstrumanlar> Enstrumanlar { get; set; }
        public virtual DbSet<Musteriler> Musteriler { get; set; }
        public virtual DbSet<Siparis_Detay> Siparis_Detay { get; set; }
        public virtual DbSet<Siparisler> Siparisler { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
