//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuzikEnstrumaniDukkani.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparis_Detay
    {
        public int Id { get; set; }
        public string Siparis_No { get; set; }
        public Nullable<int> Enstruman_Id { get; set; }
        public Nullable<int> Adet { get; set; }
    
        public virtual Enstrumanlar Enstrumanlar { get; set; }
    }
}
