//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuzikEnstrumaniDukkani.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparisler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Siparisler()
        {
            this.Destek_Talepleri = new HashSet<Destek_Talepleri>();
        }
    
        public int Id { get; set; }
        public string Siparis_No { get; set; }
        public int Musteri_Id { get; set; }
        public int Tutar { get; set; }
        public System.DateTime Siparis_Tarihi { get; set; }
        public bool Aktif { get; set; }
        public bool Iptal { get; set; }
        public bool Tamamlandi { get; set; }
        public Nullable<System.DateTime> Teslim_Tarihi { get; set; }
        public Nullable<System.DateTime> Iptal_Tarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Destek_Talepleri> Destek_Talepleri { get; set; }
        public virtual Musteriler Musteriler { get; set; }
    }
}
